#!/bin/bash

TEST_DIR=tests
ALL_TESTS=("modsys" "parser" "issues" "regression" "renamer" "mono-binds")

TESTS=()

if [ $# == 0 ]; then
  declare -a TESTS
  for i in ${!ALL_TESTS[*]}; do
    TESTS[i]="$TEST_DIR/${ALL_TESTS[i]}"
  done
else
  TESTS=("$@")
fi

CRY_VERSION=$(grep Version: cryptol.cabal | awk '{print $2}')

if [ ${CRY_VERSION}x == "x" ]; then
  echo Failed to guess version of Cryptol.
  exit 1
fi

GHC_VERSION=$(ghc --numeric-version)

if [ ${GHC_VERSION}x == "x" ]; then
  echo Failed to guess version of GHC.
  exit 1
fi

echo Testing Cryptol version ${CRY_VERSION}, built using GHC ${GHC_VERSION}.


CRY=$(find dist-newstyle -name cryptol -type f \
          | grep $GHC_VERSION \
          | grep $CRY_VERSION)


cabal new-run cryptol-test-runner -- --exe $CRY --ignore-expected ${TESTS[*]}


