[package]
name = "cry_ffi"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]
crate-type = ["lib"]

[[example]]
name = "example"
path = "src/example.rs"
crate-type = ["cdylib"]

[dependencies]
num = "0.4.0"
