name: Cryptol Dockerfile
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Cryptol Docker
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: outputs
        run: |
          changed_since="$(git log --since '23 hours 59 minutes')"
          files="${changed_since:+"$(git diff-tree --no-commit-id --name-only -r '${{ github.sha }}' | xargs)"}"
          echo "::set-output name=files::$files"
          echo "::set-output name=version::$(grep Version cryptol.cabal | awk '{print $2}')"

      - name: Publish to Registry
        if: ${{ steps.outputs.outputs.files }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: galoisinc/cryptol
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.outputs.outputs.version }}"
